src/Entity/Piece.php
<?php

namespace App\Entity;

use App\Repository\PieceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PieceRepository::class)
 */
class Piece
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="integer")
     */
    private $Quantite;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Type;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $PrixCatalogue;

    /**
     * @ORM\ManyToOne(targetEntity=Fournisseur::class, inversedBy="PiecesFournies")
     */
    private $Fournisseur;

    /**
     * @ORM\OneToOne(targetEntity=Gamme::class, mappedBy="Piece", cascade={"persist", "remove"})
     */
    private $Gamme;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $Reference;

    /**
     * @ORM\OneToMany(targetEntity=PieceRelation::class, mappedBy="PieceNecessaire", cascade={"merge", "persist"}, orphanRemoval=true)
     */
    private $PiecesNecessaires;

    /**
     * @ORM\OneToMany(targetEntity=PieceRelation::class, mappedBy="PieceProduite", cascade={"merge", "persist"}, orphanRemoval=true)
     */
    private $PiecesProduites;

    /**
     * @ORM\OneToMany(targetEntity=LigneCommandeAchat::class, mappedBy="Piece")
     */
    private $LignesCommandeAchat;

    public function __construct()
    {
        $this->Prix = null;
        $this->PrixCatalogue = null;
        $this->PiecesNecessaires = new ArrayCollection();
        $this->PiecesProduites = new ArrayCollection();
        $this->LignesCommandeAchat = new ArrayCollection();
    }

    public function __toString()
    {
        return "#".$this->getReference()." - ".$this->getLibelle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->Quantite;
    }

    public function setQuantite(int $Quantite): self
    {
        $this->Quantite = $Quantite;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(?float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getPrixCatalogue(): ?float
    {
        return $this->PrixCatalogue;
    }

    public function setPrixCatalogue(?float $PrixCatalogue): self
    {
        $this->PrixCatalogue = $PrixCatalogue;

        return $this;
    }

    public function getFournisseur(): ?Fournisseur
    {
        return $this->Fournisseur;
    }

    public function setFournisseur(?Fournisseur $Fournisseur): self
    {
        $this->Fournisseur = $Fournisseur;

        return $this;
    }

    public function getGamme(): ?Gamme
    {
        return $this->Gamme;
    }

    public function setGamme(Gamme $Gamme): self
    {
        // set the owning side of the relation if necessary
        if ($Gamme->getPiece() !== $this) {
            $Gamme->setPiece($this);
        }

        $this->Gamme = $Gamme;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->Reference;
    }

    public function setReference(string $Reference): self
    {
        $this->Reference = $Reference;

        return $this;
    }

    /**
     * @return Collection|PieceRelation[]
     */
    public function getPiecesProduites(): Collection
    {
        //dump($this->PiecesNecessaires);
        return $this->PiecesNecessaires;
    }

    public function addPiecesProduite(PieceRelation $piecesNecessaire): self
    {
        if (!$this->PiecesNecessaires->contains($piecesNecessaire)) {
            $this->PiecesNecessaires[] = $piecesNecessaire;
            $piecesNecessaire->setPieceNecessaire($this);
        }

        return $this;
    }

    public function removePiecesProduite(PieceRelation $piecesNecessaire): self
    {
        if ($this->PiecesNecessaires->removeElement($piecesNecessaire)) {
            // set the owning side to null (unless already changed)
            if ($piecesNecessaire->getPieceNecessaire() === $this) {
                $piecesNecessaire->setPieceNecessaire(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PieceRelation[]
     */
    public function getPiecesNecessaires(): Collection
    {
        //dump($this->PiecesProduites);
        return $this->PiecesProduites;
    }

    public function addPiecesNecessaire(PieceRelation $piecesProduite): self
    {
        if (!$this->PiecesProduites->contains($piecesProduite)) {
            $this->PiecesProduites[] = $piecesProduite;
            $piecesProduite->setPieceProduite($this);
        }

        return $this;
    }

    public function removePiecesNecessaire(PieceRelation $piecesProduite): self
    {
        if ($this->PiecesProduites->removeElement($piecesProduite)) {
            // set the owning side to null (unless already changed)
            if ($piecesProduite->getPieceProduite() === $this) {
                $piecesProduite->setPieceProduite(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|LigneCommandeAchat[]
     */
    public function getLignesCommandeAchat(): Collection
    {
        return $this->LignesCommandeAchat;
    }

    public function addLignesCommandeAchat(LigneCommandeAchat $lignesCommandeAchat): self
    {
        if (!$this->LignesCommandeAchat->contains($lignesCommandeAchat)) {
            $this->LignesCommandeAchat[] = $lignesCommandeAchat;
            $lignesCommandeAchat->setPiece($this);
        }

        return $this;
    }

    public function removeLignesCommandeAchat(LigneCommandeAchat $lignesCommandeAchat): self
    {
        if ($this->LignesCommandeAchat->removeElement($lignesCommandeAchat)) {
            // set the owning side to null (unless already changed)
            if ($lignesCommandeAchat->getPiece() === $this) {
                $lignesCommandeAchat->setPiece(null);
            }
        }

        return $this;
    }
}

src/Form/CommandeAchatType.php
<?php

namespace App\Form;

use App\Entity\CommandeAchat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeAchatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Libelle', TextType::class, [
                'label' => 'Libellé'
            ])
            ->add('Fournisseur')
            ->add('DatePrevue', DateTimeType::class, [
                'label' => 'Date Prévue',
                'widget' => 'single_text',
            ])
            ->add('DateEffective', DateTimeType::class, [
                'label' => 'Date Effective',
                'widget' => 'single_text',
                'required' => false
            ])
            ->add('Lignes', CollectionType::class, [
                'label' => 'Lignes',
                'entry_options' => [ 'label' => false ],
                'entry_type' => LigneCommandeAchatType::class,
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => CommandeAchat::class,
        ]);
    }
}

src/Controller/ServiceCommercial/CommandeAchatController.php
<?php

namespace App\Controller\ServiceCommercial;

use App\Entity\CommandeAchat;
use App\Form\CommandeAchatNewType;
use App\Form\CommandeAchatType;
use App\Repository\CommandeAchatRepository;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

/**
 * @Route("/commercial/commande-achat")
 */
class CommandeAchatController extends AbstractController
{
    private $snappy;
    public function __construct(Pdf $pdf){
        $this->snappy = $pdf;
    }

    /**
     *  Render in a PDF the sandbox_homepage URL
     * @Route("/topdf/{id}", name="commande_achat_to_pdf")
     * @return Response
     */
    public function pdfAction(CommandeAchat $commandeAchat)
    {
        $this->snappy->setOption('no-outline', true);
        $this->snappy->setOption('page-size','LETTER');
        $this->snappy->setOption('encoding', 'UTF-8');

        $filename = $commandeAchat->getLibelle();

        $html = $this->renderView('commande_achat/show_pdf.html.twig', ['commande_achat' => $commandeAchat]);

        return new Response(
            $this->snappy->getOutputFromHtml($html),
            200,
            array(
                'Content-Type'          => 'application/pdf',
                'Content-Disposition'   => 'inline; filename="'.$filename.'.pdf"'
            )
        );
    }

    public function validerCommande(CommandeAchat $commandeAchat){
        //Ajout de la quantité des pièces
        foreach ($commandeAchat->getLignes() as $ligne){
            $currentQte = $ligne->getPiece()->getQuantite();
            $ligne->getPiece()->setQuantite($currentQte + $ligne->getQuantite());
        }
    }

    /**
     * @Route("/", name="commande_achat_index", methods={"GET"})
     */
    public function index(CommandeAchatRepository $commandeAchatRepository): Response
    {
        return $this->render('commande_achat/index.html.twig', [
            'commande_achats' => $commandeAchatRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="commande_achat_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $commandeAchat = new CommandeAchat();
        $form = $this->createForm(CommandeAchatType::class, $commandeAchat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            foreach ($commandeAchat->getLignes() as $ligne){
                $ligne->setPrix($ligne->getPiece()->getPrixCatalogue());
            }

            //Ajout en quantité de commande, pour pas dupliqué la ligne
            $resLignes = [];

            foreach ($commandeAchat->getLignes() as $ligne){
                if(isset($resLignes[$ligne->getPiece()->getId()])) {
                    $var = $resLignes[$ligne->getPiece()->getId()];
                    $var->setQuantite($var->getQuantite() + $ligne->getQuantite());
                } else {
                    $resLignes[$ligne->getPiece()->getId()] = $ligne;
                }
            }

            $commandeAchat->getLignes()->clear();

            foreach($resLignes as $r){
                $commandeAchat->addLigne($r);
            }

            if($commandeAchat->getDateEffective())
                $this->validerCommande($commandeAchat);

            $entityManager->persist($commandeAchat);
            $entityManager->flush();

            return $this->redirectToRoute('commande_achat_index');
        }

        return $this->render('commande_achat/new.html.twig', [
            'commande_achat' => $commandeAchat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commande_achat_show", methods={"GET"})
     */
    public function show(CommandeAchat $commandeAchat): Response
    {
        return $this->render('commande_achat/show.html.twig', [
            'commande_achat' => $commandeAchat,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="commande_achat_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, CommandeAchat $commandeAchat): Response
    {
        $form = $this->createForm(CommandeAchatType::class, $commandeAchat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($commandeAchat->getLignes() as $ligne){
                $ligne->setPrix($ligne->getPiece()->getPrixCatalogue());
            }

            //Ajout en quantité de commande, pour pas dupliqué la ligne
            $resLignes = [];

            foreach ($commandeAchat->getLignes() as $ligne){
                if(isset($resLignes[$ligne->getPiece()->getId()])) {
                    $var = $resLignes[$ligne->getPiece()->getId()];
                    $var->setQuantite($var->getQuantite() + $ligne->getQuantite());
                } else {
                    $resLignes[$ligne->getPiece()->getId()] = $ligne;
                }
            }

            $commandeAchat->getLignes()->clear();

            foreach($resLignes as $r){
                $commandeAchat->addLigne($r);
            }

            if($commandeAchat->getDateEffective())
                $this->validerCommande($commandeAchat);

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('commande_achat_index');
        }

        return $this->render('commande_achat/edit.html.twig', [
            'commande_achat' => $commandeAchat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/validation/{id}", name="commande_achat_validation", methods={"POST"})
     */
    public function validation(Request $request, CommandeAchat $commandeAchat): Response
    {
        $dateEffective = new \DateTime($request->get("dateValidation"));
        $commandeAchat->setDateEffective($dateEffective);
        $this->validerCommande($commandeAchat);
        $this->getDoctrine()->getManager()->persist($commandeAchat);
        $this->getDoctrine()->getManager()->flush();

        return new JsonResponse();
    }

    /**
     * @Route("/{id}", name="commande_achat_delete", methods={"POST"})
     */
    public function delete(Request $request, CommandeAchat $commandeAchat): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commandeAchat->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($commandeAchat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('commande_achat_index');
    }
}

templates/commande_achat/_delete_form.html.twig
<form method="post" action="{{ path('commande_achat_delete', {'id': commande_achat.id}) }}" onsubmit="return confirm('Voulez vous supprimer cette commande d\'achat ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande_achat.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/commande_achat/_form.html.twig
<style>
    .card { margin: 2em 0; }
    .card .card { margin: 2em; }
    .card .card .form-group { margin: 0; }
    .card .card .card-body { display: flex; justify-content: space-between; align-items: flex-end; padding: 1em; }
    .card .card .card-body.new > div { display: flex; justify-content: space-between; width: 85%;  }
    .card .card .card-body.new > div > .form-group { width: 48%;  }
    .card .card .card-body fieldset { width: 85%; }
    .card .card .card-body .prix-total { display: flex; margin-bottom: .5em; }
    .card .card .form-group .ligne-row { display: flex; justify-content: space-between; }
    .card .card .form-group .ligne-row > .form-group { width: 48%; }
</style>

{{ form_start(form) }}
        {{ form_row(form.Libelle) }}
        {{ form_row(form.Fournisseur) }}
        {{ form_row(form.DatePrevue) }}
        {{ form_row(form.DateEffective) }}

<div class="card card-parent">
    <div class="card-header">
        Lignes de la commande
    </div>

    <div id="lignes-list" class="card-body" data-prototype="{{  form_widget(form.Lignes.vars.prototype) | e('html_attr') }}">
        {% for ligne in form.Lignes %}
            <div class="card card-ligne">
                <div class="card-body">
                    {{ form_row(ligne, { 'attr' : { 'class' : 'ligne-row' }} ) }}
                    <span class="prix-total">
                        {% if(ligne.children['Piece'].vars['data'] is not null)  %}
                            {{ ligne.children['Piece'].vars['data'].prixCatalogue * ligne.vars['data'].quantite }}€
                        {% endif %}
                    </span>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

<button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>

<script>
    var fournisseur = $("#commande_achat_Fournisseur");
    var pieces = [];
    var piece = $(".select-piece");
    var quantite = $(".input-quantite");
    var container = $(".card-parent");

    var collectionHolder;
    var addNew = $('<a class="btn btn-success"><i title="Ajouter" class="fas fa-plus"></i></a>')


    $(document).ready( function(){
        pieces = $($(`.select-piece`)[0]).find('option');

        //get the collectionHolders
        collectionHolder = $("#lignes-list");

        //append btns new
        $(".card-parent > .card-body").append(addNew)

        //add remove button to existing items
        collectionHolder.find('.card').each(function(item) {
            addRemoveButton($(this));
        });

        // handle click event du btn d'ajout
        addNew.click(function (e) {
            // création d'un nouveau form et l'append
            addNewForm();
        });

        piece.on("change", function(e){
            calculePrixTotal(this);
        });

        quantite.on("change", function(e){
            calculePrixTotal(this);
        });

        getPieceParFournisseur();
    });

    //remove item
    function addRemoveButton(item){
        var removeButton = $('<a class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>');
        var panelBtnContainer = $(item).find(".card-body").append(removeButton);

        removeButton.click(function (e) {
            $(e.target).parents('.card-ligne').slideUp(250, function() {
                $(this).remove();
            });
        });
    }

    function addNewForm(){
        var prototype = collectionHolder.data('prototype');
        var newForm = prototype;

        newForm = newForm.replace(/__name__/g, $(".card-ligne").length + 1);

        var card = $('<div class="card card-ligne"></div>');
        var cardbody = $('<div class="card-body new ligne-row"></div>').append(newForm).append('<span class="prix-total">0€</span>');
        var idCard = cardbody.children()[0].id;

        card.append(cardbody);
        addRemoveButton(card);
        addNew.before(card);

        $("#" + idCard + " .select-piece").on("change", function(e){
            calculePrixTotal(this);
        });

        $("#" + idCard + " .input-quantite").on("change", function(e){
            calculePrixTotal(this);
        });

        pieces = $("#" + idCard + " .select-piece").find('option');

        getPieceParFournisseur();
    }

    function calculePrixTotal(item){
        var quantite, prixUnit;
        var prixHolder = $(item).parents(".card-body").children(".prix-total");
        if(item.id.indexOf("Quantite") > 0) {
            quantite = $(item).val();
            prixUnit = $(item).parents(".ligne-row").find(".select-piece option:selected").data("prix");
        }
        else if(item.id.indexOf("Piece") > 0){
            prixUnit = $(item).find("option:selected").data("prix");
            quantite = $(item).parents(".ligne-row").find(".input-quantite").val();
        }

        var prix = prixUnit * quantite;
        $(prixHolder).html(parseFloat(prix).toFixed(2) + "€");
    }

    function getPieceParFournisseur(){
        var fournisseurId = fournisseur.val();
        var data = pieces.closest(`[data-fournisseur="${fournisseurId}"]`);
        $(".select-piece").empty().append(data);

        fournisseur.on("change", function(e){
            getPieceParFournisseur();
            $(".select-piece").each(function( index ) {
                calculePrixTotal(this);
            });
        });
    }

</script>
{{ form_row(form._token) }}
{{ form_end(form, {'render_rest': false}) }}

templates/commande_achat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'une commande{% endblock %}

{% block body %}
    <h1>Modification d'une commande d'achat</h1>

    {{ include('commande_achat/_form.html.twig', {'button_label': 'Enregistrer'}) }}

    <a class="btn btn-primary" href="{{ path('commande_achat_index') }}">Retour aux commandes</a>

    {{ include('commande_achat/_delete_form.html.twig') }}
{% endblock %}

templates/commande_achat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CommandeAchat index{% endblock %}

{% block body %}
    {% set prixTotal = 0 %}

    <style>
        .d-flex a { margin-right: .5em; }
    </style>

    <h1>CommandeAchat index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Libellé</th>
                <th>Fournisseur</th>
                <th>Date Prévue</th>
                <th>Date Effective</th>
                <th>Prix</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commande_achats %}
            <tr>
                <td>{{ commande.Libelle }}</td>
                <td>{{ commande.Fournisseur }}</td>
                <td>{{ commande.DatePrevue ? commande.DatePrevue|date('d/m/Y à H:i') : '' }}</td>
                <td>{{ commande.DateEffective ? commande.DateEffective|date('d/m/Y à H:i') : 'Non validé' }}</td>
                <td>{{ commande | prixTotal }}€</td>
                <td>
                    <div class="d-flex">
                        <a class="btn btn-primary" href="{{ path('commande_achat_show', {'id': commande.id}) }}"><i class="fas fa-search"></i></a>
                        {% if(not commande.DateEffective) %}
                            <a class="btn btn-primary" href="{{ path('commande_achat_edit', {'id': commande.id}) }}"><i class="fas fa-edit"></i></a>
                            <a class="btn btn-success" title="Validation" data-toggle="modal" data-target="#modal-validation" data-commande="{{ commande.id }}"><i class="fas fa-check"></i></a>
                            <form method="post" action="{{ path('commande_achat_delete', {'id': commande.id}) }}" onsubmit="return confirm('Voulez vous supprimer cette commande d\'achat ?');">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commande.id) }}">
                                <button class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
                            </form>
                        {% endif %}
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="d-flex">
        <a class="btn btn-primary" href="{{ path('accueil') }}">Retour</a>
        <a class="btn btn-primary" href="{{ path('commande_achat_new') }}">Ajouter une commande</a>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modal-validation" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Valider la commande</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form>
                    <div class="modal-body">
                        <input id="modal-validation-date" class="form-control" name="dateValidation" type="datetime-local" required/>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                        <button id="modal-validation-save" type="submit" class="btn btn-primary">Enregistrer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script>
        $('#modal-validation').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var commandId = button.data('commande');
            var url = "{{ path('commande_achat_validation', {'id': 'commandId' }) }}".replace('commandId', commandId);

            $("#modal-validation-save").off("click");
            $("#modal-validation-save").on("click", function(e) {
                var dateEffective = $('#modal-validation-date').val();
                console.log("dateEffective", dateEffective);
                if(!!dateEffective) {
                    $.post(url, {'dateValidation': dateEffective}, function(res){

                    });
                }
            });
        });


    </script>
{% endblock %}

templates/commande_achat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'une commande d'achat{% endblock %}

{% block body %}
    <h1>Ajout d'une commande d'achat</h1>

    {{ include('commande_achat/_form.html.twig') }}

    <a class="btn btn-primary" href="{{ path('commande_achat_index') }}">Retour aux commandes</a>
{% endblock %}